export interface IAlerta{
  Titulo: string,
  Conteudo: string,
  Cor: string,
  BotaoCancelar: boolean,
  TextoBotaoCancelar: string,
  CorBotaoCancelar: string,
  CorTextoBotaoCancelar: string,
  BotaoConfirmar: boolean,
  TextoBotaoConfirmar: string,
  CorBotaoConfirmar: string,
  CorTextoBotaoConfirmar: string,
  Timeout: number,
  CorBarraTimer: string,
}
